## 2019-02-11

### What did you do this week?

- Rachel: 

- Ru: 

- Maggie: Worked on a method of web scraping that could work with the task on hand, but was problematic because it was largely manual. Talked to our contact at ProPublica and determined what our goals were with her and what her expectations were of us. Worked on a datacamp course regarding webscraping, which we believe will be our main task after talking to our contact. Particularly, I worked on trying to understand Selenium for R, because that was suggested to us by our contact, and tried to determine if this would work with our project.

### What is it that you're struggling with right now?

- Rachel: 


- Ru: 

- Maggie: Right now, I am trying to determine a better way of web scraping the website containing the names of doctors that works with the formatting of the website, because our current method is based mostly around the manual collection and input of data.

### What are you planning to do next week?

- Rachel: 

- Ru:   

- Maggie: Do more research on Selenium and start working with it or a similar program to try to scrape the website for relevant data for our client.
