---
title: "Next button"
author: "Ru"
date: "3/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSelenium)
library(xml2)
library(rvest)
library(dplyr)
```

> Create a next button
> Click next 
> Wait a little bit, until the page has loaded 
> automatically click next using RSelenium 

```{r, include = FALSE}
remDr <- remoteDriver(remoteServerAddr = "localhost",
                                port = 4445L,
                                browserName = "chrome")
remDr$open()

```




```{r, include=FALSE}
url = "https://my.uscis.gov/findadoctor"

#First step: Opening chrome in a web browser, and navigating to our page
rD <- rsDriver(chromever ="73.0.3683.68")
 remDr <- rD[["client"]]
   #navigate to the webpage 
   remDr$navigate(url)
   
   
   #find the search bar where we put in zipcode
   zipElem <- remDr$findElement("css selector","#form_data_search_location")
   #let RSelenium type in the zipcode and search 
   zipElem$sendKeysToElement(list("01063","\uE007"))  #"\uE007" is the key for "ENTER"
```


#using for loop to click next 
```{r}
doc_name = c()
doc_address = c()
doc_city = c()
doc_phone = c()
multi_name =c()


for(i in 1:4){
names = xml2::read_html(remDr$getPageSource()[[1]])%>%
  rvest::html_nodes(".name")%>%
  rvest::html_text(trim = TRUE)
doc_name = c(doc_name,names)

mnames = xml2::read_html(remDr$getPageSource()[[1]])%>%
  rvest::html_nodes(".doctors-div")%>%
  rvest::html_nodes(".doctor-name")%>%
  rvest::html_text(trim = TRUE)
multi_name = c(multi_name,mnames)

address <- xml2::read_html(remDr$getPageSource()[[1]])%>%
  html_nodes(".address_top")%>%
  html_text(trim = TRUE)
doc_address = c(doc_address,address)

city <- xml2::read_html(remDr$getPageSource()[[1]])%>%
  html_nodes(".address_bottom")%>%
  html_text(trim = TRUE)
doc_city = c(doc_city, city)

phone <- xml2::read_html(remDr$getPageSource()[[1]])%>%
  html_nodes(".telephone")%>%
  html_text(trim = TRUE)
doc_phone = c(doc_phone,phone)
  Sys.sleep(1)
remDr$findElement("css selector","#populated_addresses > div:nth-child(11) > div > div.next > button")$clickElement()
Sys.sleep(1)
}
#View(multi_name)
```


#multiple doctors





```{r}
scrapeddf <- data.frame(doc_name, doc_address,doc_city)
uscisdf_end <- scrapeddf[!scrapeddf$doc_name=="",]
uscisdf_phone <- data.frame(uscisdf, doc_phone)
write.csv(uscisdf_end,"uscisdf_actual.csv")
View(uscisdf_end)
View(doc_phone)
```


#close and stop the server
```{r}
remDr$close()
   # stop the selenium server
   rD[["server"]]$stop()
```
```

